#from collections import OrderedDict

playnames = {

"All's Well That Ends Well (1602)":"xml/all_well.xml",
"Antony and Cleopatra (1606)":	    "xml/a_and_c.xml",
"As You Like It (1599)":			"xml/as_you.xml",
"Comedy of Errors (1589)":			"xml/com_err.xml",
"Coriolanus (1607)":			    "xml/coriolan.xml",
"Cymbeline (1609)":			    "xml/cymbelin.xml",
"Hamlet (1600)":			        "xml/hamlet.xml",
"Henry IV, Part I (1597)":            "xml/hen_iv_1.xml",
"Henry IV, Part II (1597)":		"xml/hen_iv_2.xml",
"Henry V (1598)":				    "xml/hen_v.xml",
"Henry VI, Part I (1591)":			"xml/hen_vi_1.xml",
"Henry VI, Part II (1590)":		"xml/hen_vi_2.xml",
"Henry VI, Part III (1590)":		"xml/hen_vi_3.xml",
"Henry VIII (1612)":			    "xml/hen_viii.xml",
"Julius Caesar (1599)":	        "xml/j_caesar.xml",
"King John (1596)":		        "xml/john.xml",
"King Lear (1605)":			    "xml/lear.xml",
"Love's Labour's Lost (1594)":	    "xml/lll.xml",
"Macbeth (1605)":				    "xml/macbeth.xml",
"Measure for Measure (1604)":		"xml/m_for_m.xml",
"Merchant of Venice (1596)":		"xml/merchant.xml",
"Merry Wives of Windsor (1600)":   "xml/m_wives.xml",
"Midsummer Night's Dream (1595)":	"xml/dream.xml",
"Much Ado about Nothing (1598)":	"xml/much_ado.xml",
"Othello (1604)":				    "xml/othello.xml",
"Pericles (1608)":				    "xml/pericles.xml",
"Richard II (1595)":	            "xml/rich_ii.xml",
"Richard III (1592)":			    "xml/rich_iii.xml",
"Romeo and Juliet (1594)":			"xml/r_and_j.xml",
"Taming of the Shrew (1593)":		"xml/taming.xml",
"Tempest (1611)":				    "xml/tempest.xml",
"Timon of Athens (1607)":			"xml/timon.xml",
"Titus Andronicus (1593)":			"xml/titus.xml",
"Troilus and Cressida (1601)":	    "xml/troilus.xml",
"Twelfth Night (1599)":		    "xml/t_night.xml",
"Two Gentlemen of Verona (1594)":	"xml/two_gent.xml",
"Winter's Tale (1610)":			"xml/win_tale.xml"
}
